title: Vinoth Sukumaran
author: vinoth sukumaran
email: vinoth.suku@hotmail.com
url: https://vinothsuku.github.io
baseurl: "/"
description: >
  I ğŸ¤ Data & Analytics. In this minimalist website, you could find my posts related to my interest areas of Machine Learning, Data Science, GenAi, Edge Computing, Cycling, Books and Gardening.
  
  <a href='mailto:vinoth.suku@hotmail.com'>email</a> / <a href='https://www.linkedin.com/in/vinoth-sukumaran-540514100/'>linkedin</a> / <a href='https://github.com/Vinothsuku'>github</a> / <a href='https://twitter.com/vinothadarsh'>twitter</a> / <a href='https://vinothsuku.medium.com/'>Medium</a>

permalink: /:slug.html

favicon: "favicon.ico"
goat_counter: "vinoth"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: "ğŸ¡"
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
